version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sm_user
      POSTGRES_PASSWORD: sm_password
      POSTGRES_DB: service_manager
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
  customers:
    build:
      context: ../services/jobs
    environment:
      PORT: 45650
  jobs:
    build:
      context: ../services/jobs
    environment:
      PORT: 45651