FROM golang:1.16 AS build
WORKDIR /src/
RUN go mod vendor
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app main.go

FROM alpine:latest
RUN apk --no-cache ca-certificates
WORKDIR /root/
COPY --from=build /src/app ./
CMD ["./app"]